services:
  App\Application\Http\Handler\PingHandler:
  App\Application\Http\Handler\ListToggles:
  App\Application\Http\Handler\GetToggle:

  React\Http\Server:
    factory: App\Container\ServerFactory

  Trowski\ReactFiber\FiberLoop:
    factory: App\Container\FiberLoopFactory

parameters:
  debug: false
  config_cache_enabled: true
  monolog:
    handlers:
      default:
        type: 'stream'
        options:
          stream: 'php://stdout'
          level: 400
  server:
    max_concurrency: 512
    buffer_size: 256
    workers: 4
