services:
  App\Application\Http\Handler\PingHandler:
  App\Application\Http\Handler\ListToggles:
  App\Application\Http\Handler\GetToggle:

  Psr\EventDispatcher\EventDispatcherInterface:
    factory: Antidot\Event\Container\AsyncEventDispatcherFactory

parameters:
  debug: false
  config_cache_enabled: true
  monolog:
    handlers:
      default:
        type: 'echo'
        options:
          level: 400
  server:
    host: '0.0.0.0'
    port: 5555
    workers: 8
