version: "3"

volumes:
  redis:
  app:

services:
  php:
    build: ./docker/php/
    ports:
      - 5555:5555
    links:
      - redis
      - postgres
    volumes:
      - redis:/var/lib/redis
      - ./:/opt
    working_dir: /opt
    command: ["php", "/opt/public/index.php"]

  redis:
    image: redis:latest
    volumes:
      - redis:/var/lib/redis

  postgres:
    image: 'postgres:13.3'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'