version: "3"

volumes:
  redis:
  postgres_data:

services:
  php:
    build: ./docker/php/
    ports:
      - 5555:5555
    links:
      - postgres
    volumes:
      - redis:/var/lib/redis
      - ./:/opt
    working_dir: /opt
    environment:
      XDEBUG_MODE: 'off'
    command: ["bin/console", "serve"]

  postgres:
    build: ./docker/postgres/
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
